"""Commit message

Revision ID: 2a2396b40451
Revises: 7cb9e7bd7f0d
Create Date: 2022-12-20 16:46:22.363329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2396b40451'
down_revision = '7cb9e7bd7f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
